server:
  port: 8085

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456aA@
      connect-timeout: 60000
#  cloud:
#    gateway:
#      server:
#        webflux:
#          globalcors:
#            add-to-simple-url-handler-mapping: true
#            cors-configurations:
#              '[/**]':
#                allowedOrigins: "http://localhost:4200"
#                allowedMethods: "*"
#                allowedHeaders: "*"
#                allowCredentials: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    ecommerce.gateway.filter.JwtGlobalFilter: INFO
    org.springframework.cloud.gateway.filter.ForwardPathFilter: DEBUG
